// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function FormatJSON(arg1:string):Promise<string>;

export function SendRequest(arg1:services.APIRequest):Promise<services.APIResponse>;

export function StartSubscription(arg1:services.SubscriptionRequest):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopSubscription(arg1:string):Promise<void>;
