// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function FormatJSON(arg1:string):Promise<string>;

export function SendRequest(arg1:services.APIRequest):Promise<services.APIResponse>;
