// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatJSON(arg1) {
  return window['go']['services']['CallAPIService']['FormatJSON'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['services']['CallAPIService']['SendRequest'](arg1);
}
