// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGoogleDriveSyncStatus() {
  return window['go']['main']['App']['CheckGoogleDriveSyncStatus']();
}

export function CopySavedAPI(arg1) {
  return window['go']['main']['App']['CopySavedAPI'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteSavedAPI(arg1) {
  return window['go']['main']['App']['DeleteSavedAPI'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetActiveWorkspace() {
  return window['go']['main']['App']['GetActiveWorkspace']();
}

export function GetCloudSyncState() {
  return window['go']['main']['App']['GetCloudSyncState']();
}

export function GetGoogleDriveConfig() {
  return window['go']['main']['App']['GetGoogleDriveConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSavedAPIs() {
  return window['go']['main']['App']['ListSavedAPIs']();
}

export function ListSavedCollections() {
  return window['go']['main']['App']['ListSavedCollections']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadEnvironmentStore() {
  return window['go']['main']['App']['LoadEnvironmentStore']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function MoveFolder(arg1) {
  return window['go']['main']['App']['MoveFolder'](arg1);
}

export function OpenJSONFile() {
  return window['go']['main']['App']['OpenJSONFile']();
}

export function PullWorkspacesFromGoogleDrive() {
  return window['go']['main']['App']['PullWorkspacesFromGoogleDrive']();
}

export function RenameCollection(arg1) {
  return window['go']['main']['App']['RenameCollection'](arg1);
}

export function RenameFolder(arg1) {
  return window['go']['main']['App']['RenameFolder'](arg1);
}

export function RenameSavedAPI(arg1, arg2) {
  return window['go']['main']['App']['RenameSavedAPI'](arg1, arg2);
}

export function RequestGoogleDriveAccess() {
  return window['go']['main']['App']['RequestGoogleDriveAccess']();
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveEnvironmentStore(arg1) {
  return window['go']['main']['App']['SaveEnvironmentStore'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['main']['App']['SaveFolder'](arg1);
}

export function SaveGoogleDriveConfig(arg1) {
  return window['go']['main']['App']['SaveGoogleDriveConfig'](arg1);
}

export function SaveJSONFile(arg1, arg2) {
  return window['go']['main']['App']['SaveJSONFile'](arg1, arg2);
}

export function SaveSavedAPI(arg1) {
  return window['go']['main']['App']['SaveSavedAPI'](arg1);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function SyncAllWorkspacesToGoogleDrive() {
  return window['go']['main']['App']['SyncAllWorkspacesToGoogleDrive']();
}
