// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckGoogleDriveSyncStatus():Promise<main.CloudSyncState>;

export function CopySavedAPI(arg1:main.CopySavedAPIRequest):Promise<main.SavedAPI>;

export function CreateWorkspace(arg1:string):Promise<main.Workspace>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteFolder(arg1:main.FolderPathRequest):Promise<void>;

export function DeleteSavedAPI(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<main.Workspace>;

export function GetActiveWorkspace():Promise<main.Workspace>;

export function GetCloudSyncState():Promise<main.CloudSyncState>;

export function GetGoogleDriveConfig():Promise<main.GoogleDriveConfigView>;

export function Greet(arg1:string):Promise<string>;

export function ListSavedAPIs():Promise<Array<main.SavedAPI>>;

export function ListSavedCollections():Promise<Array<main.SavedCollection>>;

export function ListWorkspaces():Promise<Array<main.Workspace>>;

export function LoadEnvironmentStore():Promise<main.EnvironmentStore>;

export function LoadState():Promise<main.AppState>;

export function MoveFolder(arg1:main.MoveFolderRequest):Promise<main.SavedCollection>;

export function OpenBugReportAttachmentFile():Promise<main.BugReportAttachment>;

export function OpenJSONFile():Promise<main.JSONFileResult>;

export function PullWorkspacesFromGoogleDrive():Promise<main.CloudSyncState>;

export function RenameCollection(arg1:main.RenameCollectionRequest):Promise<main.SavedCollection>;

export function RenameFolder(arg1:main.RenameFolderRequest):Promise<main.SavedCollection>;

export function RenameSavedAPI(arg1:string,arg2:string):Promise<void>;

export function RequestGoogleDriveAccess():Promise<main.CloudSyncState>;

export function SaveCollection(arg1:string):Promise<main.SavedCollection>;

export function SaveEnvironmentStore(arg1:main.EnvironmentStore):Promise<void>;

export function SaveFolder(arg1:main.SavedFolderRequest):Promise<main.SavedCollection>;

export function SaveGoogleDriveConfig(arg1:main.GoogleDriveConfigRequest):Promise<main.GoogleDriveConfigView>;

export function SaveJSONFile(arg1:string,arg2:string):Promise<string>;

export function SaveSavedAPI(arg1:main.SavedAPI):Promise<main.SavedAPI>;

export function SaveState(arg1:string):Promise<string>;

export function SubmitBugReport(arg1:main.BugReportRequest):Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<main.Workspace>;

export function SyncAllWorkspacesToGoogleDrive():Promise<main.CloudSyncState>;
